name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-node:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Package Registry
        run: |
          cd node
          cat package.json
          echo "Publish to GitHub Package Registry"
          export NODE_AUTH_TOKEN=${{secrets.GITHUB_TOKEN}}
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
